In [11]:
import pandas as pd
from pathlib import Path
workbook_path = Path("Venter_Analysis.xlsx")
if not workbook_path.exists():
    alt_path = Path("Vender Analysis") / "Venter_Analysis.xlsx"
    if alt_path.exists():
        workbook_path = alt_path
collections_df  = pd.read_excel(workbook_path, sheet_name=["Collections"])
items_df  = pd.read_excel(workbook_path, sheet_name=["Items"])
collections_df = collections_df["Collections"]
items_df = items_df["Items"]

print("\nItems Columns:", items_df.columns.tolist())

print("\nCollections Columns:", collections_df.columns.tolist())

Items Columns: ['Picture', 'Id', 'Name', 'Secondary Name', 'Price', 'Description', 'Secondary Description', 'Price_IQD', 'Sheet', 'Price_PKR']

Collections Columns: ['Item Id', 'Item Name', 'Secondary Item Name', 'Price', 'Is Active', 'Picture', 'Sheet', 'Price_IQD', 'Price_PKR']

In [13]:

collections_df = collections_df.drop(
    columns=["Color Code", "Size", "Unit Level", "Code", "Barcode","Picture","Is Active"],
    errors='ignore'
)

In [10]:
collections_df

,Item Id,Item Name,Secondary Item Name,Price,Color,Secondary Color,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,"420,000د.ع",100 مل,100 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,"300,000د.ع",50 مل,50 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك,The Glow Stick,"19,750د.ع",24 سباركلينج بيج,24 Sparkling Beige,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك,The Glow Stick,"19,750د.ع",25 روز جليم,25 Rose Gleam,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك,The Contour Stick,"19,750د.ع",30,30,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل,Instant Anti Age Eraser Concealer 6 ml,"17,250د.ع",03 معتدل,03 Fair,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,"17,000د.ع",500 مل,500 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,"6,500د.ع",88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,"17,000د.ع",500 مل,500 ml,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,"6,500د.ع",88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...

In [11]:
# Combine Name + Brand
items_df["Name"] = items_df["Name"].str.cat(items_df["Brand"], sep=" - ")

# Combine Secondary Name + Secondary Brand
items_df["Secondary Name"] = items_df["Secondary Name"].str.cat(items_df["Secondary Brand"], sep=" - ")

items_df

,Picture,Id,Name,Secondary Name,Price,Description,Secondary Description,Brand,Secondary Brand
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل - بوبا ميلانو,"Pleasure Lip Oil 001, 5 ml - Pupa Milano","25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,بوبا ميلانو,Pupa Milano
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد - شانيل,Bleu De Chanel L'Exclusif Parfum - Chanel,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,شانيل,Chanel
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل - اخرى,Seapuri Scalpy Hair Serum 20 ml - Others,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",اخرى,Others
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل - مارك انطوان ب...,Ganymede EDP 50 ml - Marc-Antoine Barrois Paris,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,مارك انطوان باروا باريس,Marc-Antoine Barrois Paris
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل - آيتن,Brow Styling Gel With Peptides 15 ml - Ayten,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",آيتن,Ayten
...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل - ذ...,Lime & Matcha Hair & Body Mist 150 ml - The Bo...,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",ذا بودي شوب,The Body Shop
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 ...,Pink Pepper & Lychee Hair & Body Mist 150 ml -...,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,ذا بودي شوب,The Body Shop
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل - كا...,Glam & Doll Boost Lash Growth Volume Mascara 8...,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",كاتريس,Catrice
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل - بيت الصابون اللبناني,Body Mist Passion Fruit150 ml - Bayt Al Saboun,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,بيت الصابون اللبناني,Bayt Al Saboun
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل - آرتديكو,Volume Supreme Mascara (1Black) 15 ml - Artdeco,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,آرتديكو,Artdeco

In [12]:
items_df = items_df.drop(
    columns=[
        "Brand", "Secondary Brand"
    ],errors='ignore')
items_df

,Picture,Id,Name,Secondary Name,Price,Description,Secondary Description
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل - بوبا ميلانو,"Pleasure Lip Oil 001, 5 ml - Pupa Milano","25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد - شانيل,Bleu De Chanel L'Exclusif Parfum - Chanel,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل - اخرى,Seapuri Scalpy Hair Serum 20 ml - Others,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha..."
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل - مارك انطوان ب...,Ganymede EDP 50 ml - Marc-Antoine Barrois Paris,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل - آيتن,Brow Styling Gel With Peptides 15 ml - Ayten,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou..."
...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل - ذ...,Lime & Matcha Hair & Body Mist 150 ml - The Bo...,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ..."
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 ...,Pink Pepper & Lychee Hair & Body Mist 150 ml -...,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل - كا...,Glam & Doll Boost Lash Growth Volume Mascara 8...,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ..."
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل - بيت الصابون اللبناني,Body Mist Passion Fruit150 ml - Bayt Al Saboun,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل - آرتديكو,Volume Supreme Mascara (1Black) 15 ml - Artdeco,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...

In [13]:
collections_df['Secondary Item Name']=collections_df['Secondary Item Name'].str.cat(collections_df['Secondary Color'])
collections_df['Item Name']=collections_df['Item Name'].str.cat(collections_df['Color'])
collections_df

,Item Id,Item Name,Secondary Item Name,Price,Color,Secondary Color,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد100 مل,Bleu De Chanel L'Exclusif Parfum100 ml,"420,000د.ع",100 مل,100 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد50 مل,Bleu De Chanel L'Exclusif Parfum50 ml,"300,000د.ع",50 مل,50 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك24 سباركلينج بيج,The Glow Stick24 Sparkling Beige,"19,750د.ع",24 سباركلينج بيج,24 Sparkling Beige,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك25 روز جليم,The Glow Stick25 Rose Gleam,"19,750د.ع",25 روز جليم,25 Rose Gleam,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك30,The Contour Stick30,"19,750د.ع",30,30,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل03 معتدل,Instant Anti Age Eraser Concealer 6 ml03 Fair,"17,250د.ع",03 معتدل,03 Fair,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي500 مل,Healthy Gums Mouthwash Pure Mint500 ml,"17,000د.ع",500 مل,500 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي88.7 مل,Healthy Gums Mouthwash Pure Mint88.7 ml,"6,500د.ع",88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف500 مل,Fresh Breath Oral Rinse Mild Mint500 ml,"17,000د.ع",500 مل,500 ml,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف88.7 مل,Fresh Breath Oral Rinse Mild Mint88.7 ml,"6,500د.ع",88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...

In [15]:
collections_df = collections_df.drop(
    columns=[
        "Color", "Secondary Color"
    ],errors='ignore')
collections_df

,Item Id,Item Name,Secondary Item Name,Price,Sheet,Price_IQD,Price_PKR
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد100 مل,Bleu De Chanel L'Exclusif Parfum100 ml,"420,000د.ع",Collections,420000,90464.934000
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد50 مل,Bleu De Chanel L'Exclusif Parfum50 ml,"300,000د.ع",Collections,300000,64617.810000
2,364804,هايلايتر ستك24 سباركلينج بيج,The Glow Stick24 Sparkling Beige,"19,750د.ع",Collections,19750,4254.005825
3,364804,هايلايتر ستك25 روز جليم,The Glow Stick25 Rose Gleam,"19,750د.ع",Collections,19750,4254.005825
4,364793,كونتور ستك30,The Contour Stick30,"19,750د.ع",Collections,19750,4254.005825
...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل03 معتدل,Instant Anti Age Eraser Concealer 6 ml03 Fair,"17,250د.ع",Collections,17250,3715.524075
14482,316612,غسول الفم للثة الصحية بالنعناع النقي500 مل,Healthy Gums Mouthwash Pure Mint500 ml,"17,000د.ع",Collections,17000,3661.675900
14483,316612,غسول الفم للثة الصحية بالنعناع النقي88.7 مل,Healthy Gums Mouthwash Pure Mint88.7 ml,"6,500د.ع",Collections,6500,1400.052550
14484,316610,غسول فم منعش بالنعناع الخفيف500 مل,Fresh Breath Oral Rinse Mild Mint500 ml,"17,000د.ع",Collections,17000,3661.675900
14485,316610,غسول فم منعش بالنعناع الخفيف88.7 مل,Fresh Breath Oral Rinse Mild Mint88.7 ml,"6,500د.ع",Collections,6500,1400.052550

In [ ]:
# Conversion rate
conversion_rate = 0.2153927  

if 'Price' in collections_df.columns:
    collections_df['Price_IQD'] = (
        collections_df['Price']
        .astype(str)
        .str.replace("د.ع", "", regex=False)
        .str.replace(",", "", regex=False)
        .str.strip()
        .replace({"": "0", "00": "0", "01": "1"})
        .astype(float)
    )
    collections_df['Price_PKR'] = collections_df['Price_IQD'] * conversion_rate

# Preview
print("Items DF:\n", items_df.head(), "\n")
print("Collections DF:\n", collections_df.head(), "\n")

Items DF:
                                              Picture      Id  \
0  https://www.storeakmedia.com/storeak-erp/Store...  390188
1  https://www.storeakmedia.com/storeak-erp/Store...  390187
2  https://www.storeakmedia.com/storeak-erp/Store...  390186
3  https://www.storeakmedia.com/storeak-erp/Store...  390185
4  https://www.storeakmedia.com/storeak-erp/Store...  390177

                                                Name  \
0           زيت الشفاه بليجر 001، 5 مل - بوبا ميلانو
1       عطر بلو دي شانيل لي اكسكلوسيف الجديد - شانيل
2       سيروم الشعر لفروة الرأس سيابوري 20 مل - اخرى
3  عطر جانيميد اودي بارفيوم 50 مل - مارك انطوان ب...
4         جل تصفيف الحواجب مع الببتيدات 15 مل - آيتن

                                    Secondary Name       Price  \
0         Pleasure Lip Oil 001, 5 ml - Pupa Milano   25,000د.ع
1        Bleu De Chanel L'Exclusif Parfum - Chanel  300,000د.ع
2         Seapuri Scalpy Hair Serum 20 ml - Others   30,000د.ع
3  Ganymede EDP 50 ml - Marc-Antoine Barrois Paris       00د.ع
4    Brow Styling Gel With Peptides 15 ml  - Ayten   15,000د.ع

                                         Description  \
0  زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...
1  عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...
2  سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...
3  عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...
4  امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...

                               Secondary Description  Price_IQD  Sheet  \
0  Nourishing lip oil that enhances lip shine wit...    25000.0  Items
1  An elegant aromatic fragrance for men.\nFragra...   300000.0  Items
2  A lightweight, non greasy serum that treats ha...    30000.0  Items
3  An oriental spicy fragrance for both sexes.\nT...        0.0  Items
4  Give your brows a sleek, all day shape with ou...    15000.0  Items

    Price_PKR
0   5384.8175
1  64617.8100
2   6461.7810
3      0.0000
4   3230.8905

Collections DF:
    Item Id                                   Item Name  \
0   390187  عطر بلو دي شانيل لي اكسكلوسيف الجديد100 مل
1   390187   عطر بلو دي شانيل لي اكسكلوسيف الجديد50 مل
2   364804                هايلايتر ستك24 سباركلينج بيج
3   364804                     هايلايتر ستك25 روز جليم
4   364793                                كونتور ستك30

                      Secondary Item Name       Price        Sheet  Price_IQD  \
0  Bleu De Chanel L'Exclusif Parfum100 ml  420,000د.ع  Collections   420000.0
1   Bleu De Chanel L'Exclusif Parfum50 ml  300,000د.ع  Collections   300000.0
2        The Glow Stick24 Sparkling Beige   19,750د.ع  Collections    19750.0
3             The Glow Stick25 Rose Gleam   19,750د.ع  Collections    19750.0
4                     The Contour Stick30   19,750د.ع  Collections    19750.0

      Price_PKR
0  90464.934000
1  64617.810000
2   4254.005825
3   4254.005825
4   4254.005825

In [ ]:
output_dir = Path("outputs")
output_dir.mkdir(parents=True, exist_ok=True)
output_file = output_dir / "Venter_Analysis_processed.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
    items_df.to_excel(writer, sheet_name="Items", index=False)
    collections_df.to_excel(writer, sheet_name="Collections", index=False)

print("Data saved successfully to", output_file)
items_df.head()

,Picture,Id,Name,Secondary Name,Price,Description,Secondary Description,Price_IQD,Sheet,Price_PKR
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل - بوبا ميلانو,"Pleasure Lip Oil 001, 5 ml - Pupa Milano","25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,25000.0,Items,5384.8175
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد - شانيل,Bleu De Chanel L'Exclusif Parfum - Chanel,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,300000.0,Items,64617.8100
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل - اخرى,Seapuri Scalpy Hair Serum 20 ml - Others,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",30000.0,Items,6461.7810
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل - مارك انطوان ب...,Ganymede EDP 50 ml - Marc-Antoine Barrois Paris,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,0.0,Items,0.0000
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل - آيتن,Brow Styling Gel With Peptides 15 ml - Ayten,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",15000.0,Items,3230.8905

In [ ]:
items_df["Sheet"] = "Items"
collections_df["Sheet"] = "Collections"

merged_df = pd.concat([items_df, collections_df], ignore_index=True)

merged_count = len(merged_df)
print(f"Total merged rows: {merged_count}")

Total merged rows: 39188

In [ ]:

matched_df = collections_df[collections_df["Item Id"].isin(items_df["Id"])]

matched_df = matched_df[["Item Id", "Item Name", "Secondary Item Name","Price_IQD", "Price_PKR"]]

print("From Collections Sheet: \n",matched_df)

From Collections Sheet:
        Item Id                                    Item Name  \
0       390187   عطر بلو دي شانيل لي اكسكلوسيف الجديد100 مل
1       390187    عطر بلو دي شانيل لي اكسكلوسيف الجديد50 مل
2       364804                 هايلايتر ستك24 سباركلينج بيج
3       364804                      هايلايتر ستك25 روز جليم
4       364793                                 كونتور ستك30
...        ...                                          ...
14481   332027      كونسيلر فوري مضاد للشيخوخة 6 مل03 معتدل
14482   316612   غسول الفم للثة الصحية بالنعناع النقي500 مل
14483   316612  غسول الفم للثة الصحية بالنعناع النقي88.7 مل
14484   316610           غسول فم منعش بالنعناع الخفيف500 مل
14485   316610          غسول فم منعش بالنعناع الخفيف88.7 مل

                                 Secondary Item Name  Price_IQD     Price_PKR
0             Bleu De Chanel L'Exclusif Parfum100 ml   420000.0  90464.934000
1              Bleu De Chanel L'Exclusif Parfum50 ml   300000.0  64617.810000
2                   The Glow Stick24 Sparkling Beige    19750.0   4254.005825
3                        The Glow Stick25 Rose Gleam    19750.0   4254.005825
4                                The Contour Stick30    19750.0   4254.005825
...                                              ...        ...           ...
14481  Instant Anti Age Eraser Concealer 6 ml03 Fair    17250.0   3715.524075
14482         Healthy Gums Mouthwash Pure Mint500 ml    17000.0   3661.675900
14483        Healthy Gums Mouthwash Pure Mint88.7 ml     6500.0   1400.052550
14484        Fresh Breath Oral Rinse Mild Mint500 ml    17000.0   3661.675900
14485       Fresh Breath Oral Rinse Mild Mint88.7 ml     6500.0   1400.052550

[14486 rows x 5 columns]